version: '3.6'

services:

  app:
    image: node:alpine
    working_dir: /app
    command: yarn start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mongodb://mongo-crudnode:27017/noderest
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo-crudnode
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
